#!/usr/bin/python
realDataSet = "ACTGAGGTGAGATAGCCGAGATGAACAACTAAGCTCGTTCTCCATTAAACGCTTGCAAAGAAACAGCTTTCTACAACCGTAGGACCCATTGAGCCTGTGCAATGAGCCGTCCTTCAGACGCGGATGGGAACACTCTTTCTCTAAGCGTCGTATGTAGTGTGGCTACTCGCGTCGTATTCACGAAACCTCGTTTTGCCCCGTATAGGGCAGATGATAGCTTGTGGTCTTTTGCAGGAGCGGCCGAACGCACAACACAGTCTCCTAATAATCCAGACATCCTCCTCATATTCAAAAACTGCTGTATGATTGACCGTGTTCATAACTGAACCATGTTCGGAGATACCGCCTTTAAACCTGTGATCAAAAGGGAGATTAGGCCTAACGGGTTTATCCCCTGAACGGATGATATAAGCGTGAAGGCTATGGGTGACCATCATTACGTAGCTATCCGGAACCAATGTTGACAAAGGCCCCTGCGGCAAACTTCTTAGCCGCGACTGCTATCGGGAAAACCGTGCATGACCGCTATGATGCCCTGCCGCAGCACACGGAGAGTCCGGTTTTTCGTACGTGCTCACGAATCGTTTTAAATGCGGGCACTGCCACGTGCCCGTTGTCGCATTTTAAACATAACTCCGGCTTGAACTCAGTGGCAAACGGGCACTGCCAGCCGTATCTTGGGGGTTTCTCTTCCGCACATCAAACATGGTCCCCCTGACCTACTCCTGTGATAGTGCACTGAGGACACGTGAATGGAGCCTCTACACAGTAATATTTTTCTCGAGCCGGTGCCGATGTTGTGCGGTACCGCCCGTCTGCTCACGGCAAATGCTCGCTACGCCAATTCGGGGTTATCCAGAAACGATGACGCGTGCAGATCCGGGGCTGATGCCAACTAAACGGTCCAACGCAGCGTACCTTCGTACATTTACAACAATTCGTAAAAACAGACCTTCAGGAAAG"

def AtoT():
	return 'T'
def TtoA():
	return 'A'
def CtoG():
	return 'G'
def GtoC():
	return 'C'

def unknown():
	return ''

def reverseComplement2(rawData):
	l = list(rawData)
	l.reverse()
	a = []
	for s in l:
		a.append({'A':AtoT, 'T':TtoA, 'C': CtoG, 'G':GtoC}.get(s, unknown)())
	print ''.join(a)


def reverseComplement(rawData):
	l = list(rawData)
	l.reverse()
	a = []
	for s in l:
		if ('A' == s):
			a.append(s.replace('A', 'T'))
		elif ('T' == s):
			a.append(s.replace('T','A'))
		elif ('G' == s):
			a.append(s.replace('G','C'))
		elif ('C' == s):
			a.append(s.replace('C','G'))

	print ''.join(a)




reverseComplement2(realDataSet)
# reverseComplement(realDataSet)
